namespace CwLibNet.Enums;

public enum TutorialLevel
{
    // UNKNOWN(0x0)
    UNKNOWN,
    // NONE(0x1)
    NONE,
    // LEVEL_10_MOVING_OBJECTS(0x2)
    LEVEL_10_MOVING_OBJECTS,
    // LEVEL_11_CREATING_AND_DELETING_OBJECTS(0x3)
    LEVEL_11_CREATING_AND_DELETING_OBJECTS,
    // LEVEL_13_ADDING_MUSIC(0x4)
    LEVEL_13_ADDING_MUSIC,
    // LEVEL_15_CRAFT_MATERIALS_PART_1(0x5)
    LEVEL_15_CRAFT_MATERIALS_PART_1,
    // LEVEL_16_CORNER_EDITING_TOOL(0x6)
    LEVEL_16_CORNER_EDITING_TOOL,
    // LEVEL_17_CRAFT_MATERIALS_PART_2(0x7)
    LEVEL_17_CRAFT_MATERIALS_PART_2,
    // LEVEL_18_FLOOD_FILL_TOOL(0x8)
    LEVEL_18_FLOOD_FILL_TOOL,
    // LEVEL_19_SOUND_OBJECTS(0x9)
    LEVEL_19_SOUND_OBJECTS,
    // LEVEL_21_MAGIC_MOUTHS(0xa)
    LEVEL_21_MAGIC_MOUTHS,
    // LEVEL_29_DANGEROUS_STUFF(0xb)
    LEVEL_29_DANGEROUS_STUFF,
    // LEVEL_30_BOLTS(0xc)
    LEVEL_30_BOLTS,
    // LEVEL_31_SPRUNG_BOLTS(0xd)
    LEVEL_31_SPRUNG_BOLTS,
    // LEVEL_32_STRING(0xe)
    LEVEL_32_STRING,
    // LEVEL_33_ELASTIC(0xf)
    LEVEL_33_ELASTIC,
    // LEVEL_34_RODS(0x10)
    LEVEL_34_RODS,
    // LEVEL_35_SPRINGS(0x11)
    LEVEL_35_SPRINGS,
    // LEVEL_36_MOTORIZED_BOLTS(0x12)
    LEVEL_36_MOTORIZED_BOLTS,
    // LEVEL_37_OSCILLATOR_BOLTS(0x13)
    LEVEL_37_OSCILLATOR_BOLTS,
    // LEVEL_38_CHAINS(0x14)
    LEVEL_38_CHAINS,
    // LEVEL_39_PISTONS(0x15)
    LEVEL_39_PISTONS,
    // LEVEL_40_EMITTERS(0x16)
    LEVEL_40_EMITTERS,
    // LEVEL_41_BUTTON_SWITCHES(0x17)
    LEVEL_41_BUTTON_SWITCHES,
    // LEVEL_42_TWO_WAY_SWITCHES(0x18)
    LEVEL_42_TWO_WAY_SWITCHES,
    // LEVEL_43_STICKER_SWITCHES(0x19)
    LEVEL_43_STICKER_SWITCHES,
    // LEVEL_44_GRAB_SWITCH(0x1a)
    LEVEL_44_GRAB_SWITCH,
    // LEVEL_45_THREE_WAY_SWITCHES(0x1b)
    LEVEL_45_THREE_WAY_SWITCHES,
    // LEVEL_46_PROXIMITY_SWITCHES(0x1c)
    LEVEL_46_PROXIMITY_SWITCHES,
    // LEVEL_47_MAGNETIC_KEY_SWITCHES(0x1d)
    LEVEL_47_MAGNETIC_KEY_SWITCHES,
    // LEVEL_48_DISSOLVE_MATERIAL(0x1e)
    LEVEL_48_DISSOLVE_MATERIAL,
    // LEVEL_49_EXPLOSIVE_OBJECTS(0x1f)
    LEVEL_49_EXPLOSIVE_OBJECTS,
    // LEVEL_50_ROCKETS(0x20)
    LEVEL_50_ROCKETS,
    // LEVEL_51_CREATURE_KIT(0x21)
    LEVEL_51_CREATURE_KIT,
    // VIDEO_CAMERA_ZONES(0x22)
    VIDEO_CAMERA_ZONES,
    // VIDEO_CAPTURE_OBJECTS(0x23)
    VIDEO_CAPTURE_OBJECTS,
    // VIDEO_CHECKPOINTS(0x24)
    VIDEO_CHECKPOINTS,
    // VIDEO_ENTRANCE(0x25)
    VIDEO_ENTRANCE,
    // VIDEO_FLOATY(0x26)
    VIDEO_FLOATY,
    // VIDEO_GLOBAL_CONTROLS(0x27)
    VIDEO_GLOBAL_CONTROLS,
    // VIDEO_KEYS(0x28)
    VIDEO_KEYS,
    // VIDEO_POINT_BUBBLES(0x29)
    VIDEO_POINT_BUBBLES,
    // VIDEO_PRIZE_BUBBLES(0x2a)
    VIDEO_PRIZE_BUBBLES,
    // VIDEO_RACE_KIT(0x2b)
    VIDEO_RACE_KIT,
    // VIDEO_SCORING_POST(0x2c)
    VIDEO_SCORING_POST,
    // VIDEO_EYETOY(0x2d)
    VIDEO_EYETOY,
    // VIDEO_SNAPSHOT_CAM(0x2e)
    VIDEO_SNAPSHOT_CAM,
    // VIDEO_MAGIC_EYE(0x2f)
    VIDEO_MAGIC_EYE,
    // VIDEO_NO_JOIN_POST(0x30)
    VIDEO_NO_JOIN_POST 
}