using static CwLibNet4Hub.IO.Serializer.Serializer;
using CwLibNet4Hub.IO.Serializer;
namespace CwLibNet4Hub.Enums;

public class PartHistory
{
    public static readonly int BODY = 0x1;
    public static readonly int JOINT = 0x2;
    public static readonly int WORLD = 0x3;
    public static readonly int RENDER_MESH = 0x4;
    public static readonly int POS = 0x5;
    public static readonly int TRIGGER = 0x6;
    public static readonly int TRIGGER_EFFECTOR = 0x7;
    public static readonly int PAINT = 0x8;
    public static readonly int YELLOWHEAD = 0x9;
    public static readonly int AUDIO_WORLD = 0xa;
    public static readonly int ANIMATION = 0xb;
    public static readonly int GENERATED_MESH = 0xc;
    public static readonly int PARTICLE_CLUMP = 0xd;
    public static readonly int PARTICLE_EMITTER = 0xe;
    public static readonly int CAMERA_ZONE = 0xf;
    public static readonly int LEVEL_SETTINGS = 0x10;
    public static readonly int SPRITE_LIGHT = 0x11;
    public static readonly int KEYFRAMED_POSITION = 0x12;
    public static readonly int CAMERA = 0x13;
    public static readonly int SCRIPT_NAME = 0x14;
    public static readonly int CREATURE = 0x15;
    public static readonly int CHECKPOINT = 0x16;
    public static readonly int STICKERS = 0x17;
    public static readonly int DECORATIONS = 0x18;
    public static readonly int SCRIPT = 0x19;
    public static readonly int SHAPE = 0x1a;
    public static readonly int EFFECTOR = 0x1b;
    public static readonly int EMITTER = 0x1c;
    public static readonly int REF = 0x1d;
    public static readonly int METADATA = 0x1e;
    public static readonly int COSTUME = 0x1f;
    public static readonly int PARTICLE_EMITTER_2 = 0x20;
    public static readonly int CAMERA_TWEAK = 0x21;
    public static readonly int SWITCH = 0x22;
    public static readonly int SWITCH_KEY = 0x23;
    public static readonly int GAMEPLAY_DATA = 0x24;
    public static readonly int ENEMY = 0x25;
    public static readonly int GROUP = 0x26;
    public static readonly int PHYSICS_TWEAK = 0x27;
    public static readonly int NPC = 0x28;
    public static readonly int SWITCH_INPUT = 0x29;
    public static readonly int MICROCHIP = 0x2a;
    public static readonly int MATERIAL_TWEAK = 0x2b;
    public static readonly int MATERIAL_OVERRIDE = 0x2c;
    public static readonly int INSTRUMENT = 0x2d;
    public static readonly int SEQUENCER = 0x2e;
    public static readonly int CONTROLINATOR = 0x2f;
    public static readonly int POPPET_POWERUP = 0x30;
    public static readonly int POCKET_ITEM = 0x31;
    public static readonly int CREATOR_ANIM = 0x32;
    public static readonly int TRANSITION = 0x33;
    public static readonly int FADER = 0x34;
    public static readonly int ANIMATION_TWEAK = 0x35;
    public static readonly int WIND_TWEAK = 0x36;
    public static readonly int POWER_UP = 0x37;
    public static readonly int HUD_ELEM = 0x38;
    public static readonly int TAG_SYNCHRONIZER = 0x39;
    public static readonly int WORMHOLE = 0x3a;
    public static readonly int QUEST = 0x3b;
    public static readonly int CONNECTOR_HOOK = 0x3c;
    public static readonly int ATMOSHPERIC_TWEAK = 0x3d;
    public static readonly int STREAMING_DATA = 0x3e;
    public static readonly int STREAMING_HINT = 0x3f;
}